Repository SelfBanking/Licentia, pull requests merged in 2020-05, with the labels that each got.

#6 Github Actions and CI/CD with AWS Cloudfront
  .github/workflows/master.yaml
  package.json
  yarn.lock
Labels: Feature, WIP

#7 CI/CD with Github Actions
  .env.example
  .gitignore
  gulpfile.js
Labels: Feature, WIP

#10 fixed areas where naming camelcases standard was not followed, more m…
  src/pages/MainPage/components/AccountDetails/AccountDetails.js
  src/pages/MainPage/components/AccountDetails/accountDetailsStyle.js
Labels: enhancement

#11 Feature/account display info grid
  src/pages/MainPage/components/AccountDetails/AccountDetails.js
  src/pages/MainPage/components/AccountDetails/accountDetailsStyle.js
  src/pages/MainPage/styles.js
Labels: Feature

#12 Fix routing and Did some cleanup
  package.json
  src/components/Header/Header.js
  src/components/Header/styles.js
  src/components/Portis/PortisBtn.js
  src/components/Portis/package.json
  src/components/Portis/portisStyle.js
  src/components/Portis/styles.js
  src/index.js
  src/pages/App/App.js
  src/pages/App/package.json
  src/pages/Dashboard/Dashboard.js
  src/pages/Dashboard/components/Aave/Aave.js
  src/pages/Dashboard/components/Aave/Deposit_Eth/AaveDepositEth.js
  src/pages/Dashboard/components/Aave/package.json
  src/pages/Dashboard/components/AccountDetails/AccountDetails.js
  src/pages/Dashboard/components/AccountDetails/package.json
  src/pages/Dashboard/components/AccountDetails/styles.js
  src/pages/Dashboard/components/Compound/Compound.js
  src/pages/Dashboard/components/Compound/package.json
  src/pages/Dashboard/components/HeadlineMenu/HeadlineMenu.js
  src/pages/Dashboard/components/HeadlineMenu/package.json
  src/pages/Dashboard/components/HeadlineMenu/styles.css
  src/pages/Dashboard/components/Mainchart/Mainchart.js
  src/pages/Dashboard/components/Mainchart/package.json
  src/pages/Dashboard/components/Mainchart/styles.js
  src/pages/Dashboard/components/Swap/Swap.js
  src/pages/Dashboard/context/ContractContext.js
  src/pages/Dashboard/context/RatesContext.js
  src/pages/Dashboard/styles.js
  src/pages/MainPage/MainPage.js
  src/pages/MainPage/components/AccountDetails/AccountDetails.js
  src/pages/MainPage/components/Mainchart/Mainchart.js
  src/pages/MainPage/package.json
  src/pages/MainPage/styles.js
  src/pages/Overview/Overview.js
  src/pages/Overview/package.json
  src/react-app-env.d.ts
  yarn.lock
Labels: enhancement

#15 change to githbub action and added some uniswap abis
  .github/workflows/master.yaml
  src/contracts/abi/uniswap/exchange.abi.js
  src/contracts/abi/uniswap/factory.abi.js
  src/contracts/abi/uniswap/token.abi.js
  src/contracts/addresses/addresses.js
Labels: enhancement

#21 Feature/redisign n sidemenu
  src/assets/asset-borrow.png
  src/assets/asset-connect.png
  src/assets/asset-donate.png
  src/assets/asset-exchange.png
  src/assets/asset-help.png
  src/assets/asset-insure.png
  src/assets/asset-invest.png
  src/assets/asset-lend (2).png
  src/assets/asset-lend.png
  src/assets/asset-pay.png
  src/assets/asset-save-white.png
  src/assets/asset-shop.png
  src/assets/asset-trade-invest.png
  src/components/SideMenu/SideMenu.js
  src/components/SideMenu/styles.js
  src/pages/Dashboard/components/AccountDetails/styles.js
  src/pages/Dashboard/styles.js
Labels: Design, Feature

#22 redo top section. Currently statics, need to connect new modal for co…
  src/components/SideMenu/styles.js
  src/pages/App/App.js
  src/pages/Dashboard/Dashboard.js
  src/pages/Dashboard/styles.js
Labels: Design, Feature

#23 created initial modal on click of connect btn. also incorporated the …
  src/components/ConnectModal/ConnectModal.js
  src/components/ConnectModal/connectModalStyle.js
  src/components/Portis/PortisBtn.js
  src/components/SideMenu/SideMenu.js
  src/pages/Dashboard/Dashboard.js
Labels: Design, Feature

#26 created account balance get req for etherscan(ether), which displays …
  src/components/Header/Header.js
  src/context/EtherscanContext.js
  src/pages/App/App.js
  src/pages/Dashboard/Dashboard.js
  src/pages/Dashboard/components/AccountDetails/AccountDetails.js
  src/pages/Dashboard/components/EthBalance/EthBalance.js
Labels: Feature, WIP, bug

#32 added and display account balance ETH plus did clean up of some items
  gulpfile.js
  package.json
  src/components/ConnectModal/ConnectModal.js
  src/components/ConnectModal/connectModalStyle.js
  src/components/Portis/PortisBtn.js
  src/components/SideMenu/SideMenu.js
  src/components/SideMenu/styles.js
  src/context/EtherscanContext.js
  src/context/WalletContext.js
  src/index.js
  src/pages/App/App.js
  src/pages/Dashboard/Dashboard.js
  src/pages/Dashboard/components/AccountDetails/AccountDetails.js
  src/pages/Dashboard/components/AccountDetails/styles.js
  src/pages/Dashboard/components/EthBalance/EthBalance.js
  src/pages/Dashboard/components/Mainchart/styles.js
  src/serviceWorker.js
  src/services/MetaMaskService.js
Labels: Feature, bug

#33 Feature/static pages views
  package.json
  src/assets/trade/IDEX_Screenshot.png
  src/assets/trade/Paradex_Screenshot.png
  src/assets/trade/Waves_Exchange_Screenshot.png
  src/pages/App/App.js
  src/pages/Exchange/Exchange.js
  src/pages/Exchange/styles.js
  src/pages/Learn/Learn.js
  src/pages/Trade/Trade.js
  src/pages/Trade/package.json
  src/pages/Trade/styles.js
Labels: Design, Feature

#34 fixed issue, i forgot to remove setting from package.json
  package.json
Labels: bug
